### ISSUE TITLE
Test is needlessly inefficient

### ISSUE THREAD

**Issue by AshleyScirra** [colludium/construct-2-bunnymark#1]
Event 5 has a redundant 'for each bunny' condition which will needlessly degrade the performance of the entire test. Replacing it with 'Every tick' works identically and improves the score by about 300%.

BTW this test has almost nothing to do with rendering, the vast majority of the CPU time is spent running the events, so it's more accurate to call this an event performance test.

**Comment by colludium** [comment]
Updated to remove the unnecessary For-Each loop - I should have known better!  On my hardware this improved the performance by 50%.  I think that it is fair to call it a performance test, and if your computer reaches a CPU limit due to events then that's good data in itself.

**Comment by AshleyScirra** [comment]
Actually this test measures a few things. It's a bit like our old renderperfgl test which we replaced recently because of a similar issue. Really the test measures event performance, draw call performance and GPU fillrate, since the sprites aren't deliberately as tiny as possible. So the performance result is something like min(eventperf, drawcallperf, fillrateperf). This makes it hard to interpret the result, since you don't know why it's slow. For example maybe it only improved your system by 50% because you ran in to gpu fillrate limits sooner, whereas my machine had more fillrate available and ran in to a higher event performance limit. A scientific test ought to go to lengths to only test one thing, which is why C3 has separate performance tests for quadissue, fillrate etc.

To be fair this isn't your fault, it's a flaw with the approach bunnymark itself takes.

**Comment by colludium** [comment]
I agree that the bunnymark test is flawed - in not focusing on one system (GPU/CPU) it creates a venn-diagram of possible causes for a particular set of results.  Incidentally, after making this change, I found both the c2 and godot performances to be similar when compared to each other on laptop and mobile.  I tried to update my post in the forum but I can't now that it's locked.

**Comment by AshleyScirra** [comment]
The .capx in the repo is still using "for each", btw.

**Comment by colludium** [comment]
@AshleyScirra - err - I guess I uploaded the wrong archive.  All fixed now; I've also removed the unnecessary velocity condition checks, to make it more closely align with the other tests.
